#!/usr/bin/env python3
"""Reproducible generate -> train -> export -> test -> promote loop.

  python tools/pipeline.py --config tools/pipeline_example.json --generation 1 [--stage all|generate|train|test|promote]

Directory layout (root = config["root"]):
  nets/best/{value,policy}.nn      current incumbent (+ manifest.json)
  gen_N/data/selfplay.rec           data generated by the incumbent in generation N
  gen_N/train/{value,policy}/       checkpoints and logs
  gen_N/nets/{value,policy}.nn      candidate networks
  gen_N/test/                       bench and match results

The gate is a fixed-nodes match against the incumbent with the JHBR3
strength harness (tools/strength_test.py); Phase 5 adds SPRT. Generation 0
(no incumbent) promotes unconditionally.
"""
import argparse
import glob
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, ".."))


ENV = dict(os.environ)


def run(cmd, cwd=None, log=None):
    print("+", " ".join(cmd), flush=True)
    with open(log, "a") if log else open(os.devnull, "w") as f:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, env=ENV)
        f.write(p.stdout)
    if p.returncode != 0:
        print(p.stdout[-3000:])
        raise SystemExit(f"command failed: {' '.join(cmd)}")
    return p.stdout


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--generation", type=int, required=True)
    ap.add_argument("--stage", default="all", choices=["all", "generate", "train", "test", "promote"])
    args = ap.parse_args()
    cfg = json.load(open(args.config))
    root = os.path.abspath(cfg["root"])
    build = os.path.abspath(cfg.get("build", os.path.join(REPO, "build")))
    engine = os.path.join(build, "jhbr5")
    gen = os.path.join(root, f"gen_{args.generation}")
    best = os.path.join(root, "nets", "best")
    for d in ["data", "train/value", "train/policy", "nets", "test"]:
        os.makedirs(os.path.join(gen, d), exist_ok=True)
    ENV["PYTHONPATH"] = build + os.pathsep + os.environ.get("PYTHONPATH", "")
    seed = int(cfg.get("seed", 1)) + args.generation
    log = os.path.join(gen, "pipeline.log")
    stages = ["generate", "train", "test", "promote"] if args.stage == "all" else [args.stage]
    have_incumbent = os.path.exists(os.path.join(best, "value.nn"))

    if "generate" in stages:
        g = cfg["generate"]
        if not have_incumbent:
            print("no incumbent networks: skipping self-play generation (use imported data for generation 0)")
        else:
            cmd = [engine, "datagen", "--value", os.path.join(best, "value.nn"), "--policy",
                   os.path.join(best, "policy.nn"), "--out", os.path.join(gen, "data", "selfplay.rec"),
                   "--games", str(g["games"]), "--threads", str(g.get("threads", 8)),
                   "--nodes", str(g.get("nodes", 800)), "--seed", str(seed)]
            for k, v in g.get("extra", {}).items():
                cmd += [f"--{k}", str(v)]
            run(cmd, log=log)

    if "train" in stages:
        t = cfg["train"]
        shards = []
        for spec in t.get("data", []):
            shards += glob.glob(spec.format(root=root, gen=gen))
        window = int(t.get("replay_generations", 5))
        for g in range(max(0, args.generation - window + 1), args.generation + 1):
            shards += glob.glob(os.path.join(root, f"gen_{g}", "data", "*.rec"))
        shards = sorted(set(shards))
        if not shards:
            raise SystemExit("no training shards")
        for net in ["value", "policy"]:
            opts = t[net]
            cmd = [sys.executable, os.path.join(REPO, "train", "train.py"), "--net", net, "--shards"] + shards + [
                "--l1", str(opts["l1"]), "--steps", str(opts["steps"]), "--batch-size", str(opts.get("batch_size", 16384)),
                "--lr", str(opts.get("lr", 1e-3)), "--workers", str(t.get("workers", 4)), "--seed", str(seed),
                "--out", os.path.join(gen, "train", net), "--export", os.path.join(gen, "nets", f"{net}.nn")]
            if net == "value":
                cmd += ["--wdl-lambda", str(opts.get("wdl_lambda", 0.7))]
            if have_incumbent and opts.get("resume_from_incumbent", True):
                prev = os.path.join(root, f"gen_{args.generation - 1}", "train", net, "ckpt_last.pt")
                if os.path.exists(prev):
                    cmd += ["--resume", prev]
            run(cmd, log=log)

    if "test" in stages:
        t = cfg["test"]
        cand_v = os.path.join(gen, "nets", "value.nn")
        cand_p = os.path.join(gen, "nets", "policy.nn")
        out = run([os.path.join(build, "eval_positions"), cand_v, cand_p, os.path.join(REPO, "test", "legal100.sfens")], log=log)
        assert out.count("\nE\n") > 50, "candidate networks do not evaluate"
        bench = run(["sh", "-c", f"printf 'setoption name ValueNet value {cand_v}\\nsetoption name PolicyNet value {cand_p}\\nbench {t.get('bench_nodes', 20000)} {t.get('threads', 4)}\\nquit\\n' | {engine}"], log=log)
        print([l for l in bench.splitlines() if "bench threads" in l][-1])
        result = {"score": None}
        if have_incumbent:
            match_dir = os.path.join(gen, "test", "match")
            common = ["--engine-a", engine, "--engine-b", engine, "--openings", cfg["openings"],
                      "--nodes", str(t.get("nodes", 5000)), "--seed", str(seed), "--output", match_dir,
                      "--option-a", f"ValueNet={os.path.join(best, 'value.nn')}", "--option-a", f"PolicyNet={os.path.join(best, 'policy.nn')}",
                      "--option-b", f"ValueNet={cand_v}", "--option-b", f"PolicyNet={cand_p}",
                      "--option-a", f"Threads={t.get('threads', 4)}", "--option-b", f"Threads={t.get('threads', 4)}"]
            for k, v in t.get("engine_options", {}).items():
                common += ["--option-a", f"{k}={v}", "--option-b", f"{k}={v}"]
            if t.get("gate", "score") == "sprt":
                s = t.get("sprt", {})
                cmd = [sys.executable, os.path.join(REPO, "tools", "sprt_match.py")] + common + [
                    "--elo0", str(s.get("elo0", 0)), "--elo1", str(s.get("elo1", 5)),
                    "--round-pairs", str(s.get("round_pairs", 25)), "--max-pairs", str(t.get("pairs", 400))]
                rc = subprocess.run(cmd, env=ENV).returncode
                result["sprt"] = json.load(open(os.path.join(match_dir, "sprt.json")))["sprt"]
                result["sprt_accepted"] = rc == 0
                result["score"] = result["sprt"]["score"]
            else:
                run(common[:0] + [sys.executable, os.path.join(REPO, "tools", "strength_test.py")] + common +
                    ["--pairs", str(t.get("pairs", 100))], log=log)
                summary = json.load(open(os.path.join(match_dir, "summary.json")))
                # strength_test.py reports the score of engine A (the incumbent).
                result["score"] = 1.0 - float(summary["score"])
                result["summary"] = summary
        json.dump(result, open(os.path.join(gen, "test", "result.json"), "w"), indent=2)
        print("test result:", result.get("score"))

    if "promote" in stages:
        t = cfg["test"]
        res_path = os.path.join(gen, "test", "result.json")
        result = json.load(open(res_path)) if os.path.exists(res_path) else {"score": None}
        gate = float(t.get("promote_score", 0.52))
        if t.get("gate", "score") == "sprt":
            ok = not have_incumbent or bool(result.get("sprt_accepted"))
        else:
            ok = not have_incumbent or (result.get("score") is not None and result["score"] >= gate)
        if not ok:
            print(f"not promoted: score {result.get('score')} < {gate}")
            return 1
        os.makedirs(best, exist_ok=True)
        manifest_path = os.path.join(root, "nets", "manifest.json")
        manifest = json.load(open(manifest_path)) if os.path.exists(manifest_path) else {"history": []}
        entry = {"generation": args.generation, "time": time.strftime("%Y-%m-%dT%H:%M:%S"), "score_vs_previous": result.get("score")}
        for net in ["value", "policy"]:
            src = os.path.join(gen, "nets", f"{net}.nn")
            shutil.copy2(src, os.path.join(best, f"{net}.nn"))
            entry[net] = {"path": src, "sha256": sha256(src)}
        manifest["history"].append(entry)
        manifest["best"] = entry
        json.dump(manifest, open(manifest_path, "w"), indent=2)
        print(f"promoted generation {args.generation} -> {best}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
